### ISSUE TITLE
Java Unit Tests - Missing Tests

### ISSUE THREAD

**Issue by jmgasper** [topcoderinc/pxCore#151]
* No tests provided for all public methods for RTFunctionListener
* Tests missing for all public methods for RTRemoteProtocol
* Tests missing for all public methods for RTRemoteSerializer
* No tests for message passing using RTRemoteMessage
* Tests missing for all public methods for RTRemoteClientConnection

**Comment by nanke-** [comment]
@jmgasper The constructed function of RTRemoteProtocol is not public, we cannot create a object directly. Analogously, RTFunctionListener is just a interface, and RTRemoteMessage has not public constructed function.
