### ISSUE TITLE
Windows build - Freetype

### ISSUE THREAD

**Issue by jmgasper** [topcoderinc/pxCore#18]
A question from the client:

```
Freetype - why did you need to modify the externals at all, specifically freetype?
```

Let's make sure to document what changes are needed to Freetype, and ideally we should be able to use the unmodified externals version.

**Comment by conniefry** [comment]
We would like this fixed before we merge the pull request to johnrobinsn/pxCore.

**Comment by jmgasper** [comment]
@conniefry - Change has been reverted.
