### ISSUE TITLE
Windows build - artifacts

### ISSUE THREAD

**Issue by jmgasper** [topcoderinc/pxCore#20]
Build artifacts - none should be present in Git, specifically:

a. libjpeg-turbo and jconfigint.h

b. pthread - don't commit binaries. Commit unmodified source or use downloaded tarfile.

**Comment by conniefry** [comment]
We would like this fixed before we merge the pull request to johnrobinsn/pxCore.

**Comment by jmgasper** [comment]
@conniefry - We made these changes:

1. Removed the config files from libjpect-turbo
2. Added the pthread source code into external, similar to what we do for Node and other libraries
