### ISSUE TITLE
Windows build - V8 inspector usage

### ISSUE THREAD

**Issue by jmgasper** [topcoderinc/pxCore#21]
From the client below.  You should update the project and files accordingly, while still making sure that all proper debugging works as expected

```
V8 inspector: We already have it included as part of the node external; 
why is V8 inspector in the VS project? It should be removed and used from the externals.
```

**Comment by conniefry** [comment]
We would like this fixed before we merge the pull request to johnrobinsn/pxCore.

**Comment by jmgasper** [comment]
@conniefry - We have removed the v8 inspector stuff from the VS project
