### ISSUE TITLE
[$100] Questions and cleanup

### ISSUE THREAD

**Issue by jmgasper** [topcoderinc/pxCore#216]
1.  We had a question about needing these lines in the pxScene.sh file:

```
# bin files
ln -fs $externalDir/v8/out.gn/x64.release/natives_blob.bin  
ln -fs $externalDir/v8/out.gn/x64.release/snapshot_blob.bin
```

Can we build those bin files into the executable?  We don't want to change the pxScene.sh file at all.

2.  The client has asked that we rename directory `rtScriptNode` to `rtScriptV8`

3.  The client asked if it was possible to build both Node and V8 into a single executable.  It's not a big deal if we don't currently support it, but I'd like to know just what the level of effort would be to support it, thanks.

**Comment by jmgasper** [comment]
Contest https://www.topcoder.com/challenges/30068329 has been created for this ticket.

**Comment by jmgasper** [comment]
Contest https://www.topcoder.com/challenges/30068329 has been updated - the new changes has been updated for this ticket.

**Comment by jmgasper** [comment]
Contest https://www.topcoder.com/challenges/30068329 has been updated - the new changes has been updated for this ticket.

**Comment by jmgasper** [comment]
@krunt, please sign-up with Topcoder X tool

**Comment by jmgasper** [comment]
@krunt - Can you go to this link and and give access to Topcoder X please?

https://x.topcoder.com/api/v1/github/teams/registration/48c2ed06-ab53-4dee-a98b-eebcde50f17b-1532985120810

**Comment by krunt** [comment]
I am getting this error: '"Failed to add team member. 422 error making request PUT https://api.github.com/teams/2842481/memberships/krunt: \"Unprocessable Entity\"."

**Comment by krunt** [comment]
when signed up on https://x.topcoder.com/#/auth
it writes up 'Current user doesn't have permissions.'
