### ISSUE TITLE
[$100] Integrate MIME files back into the app

### ISSUE THREAD

**Issue by jmgasper** [topcoderinc/pxCore#221]
@jiangliwu - I got confirmation that the files we currently host in the `mime-server` are going to need to be integrated into the app, not hosted externally.  Can we roll those changes back and include those JS files back into the app please?

**Comment by jiangliwu** [comment]
@jmgasper MR pushed, https://gitlab.com/hercules-sparkdown/sparkdown/merge_requests/5
