### ISSUE TITLE
[$150] In Spark-V8, couples of tests are failing in testRunner.

### ISSUE THREAD

**Issue by spackianathan** [topcoderinc/pxCore#237]
In Spark-V8, couples of tests are failing in testRunner.
Tested in Mac.

https://px-apps.sys.comcast.net/pxscene-samples/examples/px-reference/test-run/testRunner_v7.js?tests=file:///Users/samuel/pxcore/tests/pxScene2d/testRunner/tests.json

Attached the Spark logs.

[Spark_log.txt](https://github.com/topcoderinc/pxCore/files/2590163/Spark_log.txt)

(https://github.com/topcoderinc/pxCore/files/2590159/Spark_log.txt)
<img width="1270" alt="screen shot 2018-11-16 at 10 15 28 am" src="https://user-images.githubusercontent.com/36474645/48635066-1c5c2580-e995-11e8-9868-fc494d9d1252.png">

**Comment by jmgasper** [comment]
@spackianathan - Do these also fail in the Node version of the app, or does it work fine?

**Comment by spackianathan** [comment]
Tests are passing in Node Version of Spark App. The above issue is observed only in V8 - Spark.
