### ISSUE TITLE
[$550] Spark-V8 in Linux: 40 tests are failing in testRunner.

### ISSUE THREAD

**Issue by spackianathan** [topcoderinc/pxCore#241]
Spark-V8 in Linux: 40 tests are failing in testRunner.

**This issue is NOT observed in Node Version of Spark in Linux and all the tests in testRunner are passing in Node.**

Please find attached the Spark logs below for the testRunner failures.
[spark_log_V8.txt](https://github.com/topcoderinc/pxCore/files/2621738/spark_log_V8.txt)

![capture](https://user-images.githubusercontent.com/36474645/49109774-958f2e80-f259-11e8-9122-a76fe81309d7.PNG)

**Comment by jmgasper** [comment]
@jiangliwu - Can you create a pull request against the latest in the `master` branch of this fork please?  There are some recent merge conflicts.

**Comment by jmgasper** [comment]
Looks good.
