### ISSUE TITLE
Spark-V8 in Linux : App crashes while running testRunner(Intermittent Issue)

### ISSUE THREAD

**Issue by spackianathan** [topcoderinc/pxCore#243]
Spark-V8 in Linux : App crashes while running testRunner(Intermittent Issue)

**This crash was not observed in Node version of Spark in Linux, only the V8 build (SUPPORT_V8=ON in cmake)**

Please find below Crash logs in Console:
[Crash_logs.txt](https://github.com/topcoderinc/pxCore/files/2621793/Crash_logs.txt)

Below is the Spark Logs:
[Spark_logs.txt](https://github.com/topcoderinc/pxCore/files/2621798/Spark_logs.txt)

To run the tests, use the `Spark` CLI app in `examples/pxscene2d/src` after building.  Change the file path to match your local pxCore setup.

`./Spark https://px-apps.sys.comcast.net/pxscene-samples/examples/px-reference/test-run/testRunner_v7.js?tests=file:///home/justin/pxcore/tests/pxScene2d/testRunner/tests.json`

**Comment by jmgasper** [comment]
@spackianathan - Sorry for the delay.  I've had a couple people look at this and couldn't reproduce the issue.  I'll open an F2F to get more eyes on it.
