### ISSUE TITLE
Spark-V8 in Linux: Lot of text characters are missing in about.js

### ISSUE THREAD

**Issue by spackianathan** [topcoderinc/pxCore#251]
Tested the latest Spark-V8 build in Linux.
Lot of text characters are missing in about.js

This issue is not observed in Node version of Spark.

### Things to note:

1.  This *only* happens sporadically, when the `browser.js` file is loaded and *then* the user inputs `about.js` into the address bar in pxScene

2.  This does *not* happen if about.js is loaded directly, like `./spark about.js`

### Requirements

What we are looking for here is a code fix.  Please submit a fix for the C++ and / or Javascript code.  

Do not submit:

* Configuration or DNS changes 
* Too much information that makes it hard to determine what the fix is

### Details

Please find below the spark logs and screenshot.

[Spark_logs_aboutjs.txt](https://github.com/topcoderinc/pxCore/files/2696514/Spark_logs_aboutjs.txt)

![capture](https://user-images.githubusercontent.com/36474645/50248570-6d52a580-03a9-11e9-9315-94c0d78bacb4.PNG)

**Comment by jmgasper** [comment]
@spackianathan - That's a new one.  Is this in a VM or on a real computer?  What version of Ubuntu?

**Comment by spackianathan** [comment]
Attaching the Linux SparkV8 build for reference.

[LinuxSparkV8.tar.gz](https://github.com/topcoderinc/pxCore/files/2696585/LinuxSparkV8.tar.gz)

**Comment by JDK88** [comment]
![image](https://user-images.githubusercontent.com/26185691/50338408-31594500-054f-11e9-97d1-a0f4b0c8c4c0.png)
cannot repo  @spackianathan  
I build it in ubuntu 14.04 in VirtualBox

**Comment by JDK88** [comment]
![image](https://user-images.githubusercontent.com/26185691/50350401-0801de80-057a-11e9-9718-2403155603a3.png)
I build it again, and on Ubuntu 16.04 in VirtualBox @spackianathan 
Still show the text correctly.

**Comment by spackianathan** [comment]
You are building Node version of Spark. There is no issue in Node Version of Spark.

The issue I have reported is with V8 Only version of Spark.

**Comment by ojasgulati** [comment]
hi, I am kind of new here. How to build v8 version of spark.Is there any document for it?

**Comment by tmalbonph** [comment]
> I build it again, and on Ubuntu 16.04 in VirtualBox @spackianathan
> Still show the text correctly.

It must show V8 and not "node/V8"
![spark_dev_v8_about_us](https://user-images.githubusercontent.com/3745678/50371570-74bbbe00-05f8-11e9-9521-92c803fe2a09.png)

**Comment by tmalbonph** [comment]
The missing text really exist. I have updated 3 files to fix the missing text. The solution will fix the missing text when running browser.js and display the About dialog from about.js. The solution also will fix the missing text and scrollbar when displaying a markup file.

> The above issue is not only specific to about.js.
> The text character missing issue is observed in other unit tests as well.

The missing text really exist. I have updated some files to fix the missing text. The solution will fix the missing text when running browser.js and display the About dialog from about.js. The solution also will fix the missing text and scrollbar when displaying a markup file.
![github-issue-251](https://user-images.githubusercontent.com/3745678/50961863-cc688d80-1503-11e9-8d81-792514ce1c1a.png)

**Comment by spackianathan** [comment]
Missing text issue is not observed in Retest. 

Thanks for fixing this issue.

**Comment by spackianathan** [comment]
@jmgasper While testing in https://github.com/topcoderinc/pxCore/ the above issue is not reproduced. 
Commit #: `d331293c82ce39f0263a986f811e014379a7a38b`

But while testing in https://github.com/pxscene/pxCore , I am still able to reproduce the issue.
commit # :   `c7441ca7daf5fddc64820d0d56e8558b08bc761d`

Is this fix merged to pxscene site?

**Comment by jmgasper** [comment]
@spackianathan - Yeah, they should be the same now.   Can you post an updated screenshot please?  Is this in a VM?

**Comment by spackianathan** [comment]
Yes. Tested in VM ubuntu 16.04.

Please find below the latest screenshot.
commit # : `c7441ca7daf5fddc64820d0d56e8558b08bc761d`

Note  : This issue is only observed after launching the Spark and then changing the URL to about.js 

Issue is not observed when launching by `./Spark about.js`

<img width="1437" alt="screen shot 2019-02-11 at 5 08 20 pm" src="https://user-images.githubusercontent.com/36474645/52597030-c413b300-2e1f-11e9-8b17-fc40902927a0.png">

**Comment by tmalbonph** [comment]
> Yes. Tested in VM ubuntu 16.04.
> 
> Please find below the latest screenshot.
> commit # : `c7441ca7daf5fddc64820d0d56e8558b08bc761d`
> 
> Note : This issue is only observed after launching the Spark and then changing the URL to about.js
> 
> Issue is not observed when launching by `./Spark about.js`
> 
> <img alt="screen shot 2019-02-11 at 5 08 20 pm" width="1437" src="https://user-images.githubusercontent.com/36474645/52597030-c413b300-2e1f-11e9-8b17-fc40902927a0.png">

You still having error because the solution I have provided is not yet merge into the pxScene (commit hash 598b7bba081f7358a2a5b42690598abccaa6cb06)

**Comment by spackianathan** [comment]
Thanks @tmalbonph 
@jmgasper Can you please check and merge this fix to pxScene.
