### ISSUE TITLE
[$140] Investigate Markdown processing

### ISSUE THREAD

**Issue by jmgasper** [topcoderinc/pxCore#256]
@jiangliwu - This was reported by the client.  This seems weird to me, but I'm seeing the same with the version downloaded from www.pxscene.org.  Can you take a look please?

Regressions ?

italics.md 
*italics*

blockquote.md 
> blockquote

@hfitzpatrick - Is that on the latest prod version?  That’s odd - it was working just fine in my table testing…

Hugh Fitzpatrick [11:00 AM]
This is using the Decoders hosted on pxscene.org/mime/viewMarkdown.js.  (I think)
Yeah ... URL above is correct

Possible version mix up ???

![screen shot 2018-12-21 at 3 49 55 pm](https://user-images.githubusercontent.com/21790/50381026-fdf1f400-06cf-11e9-9597-605f8d1badf9.png)

![screen shot 2018-12-21 at 3 49 20 pm](https://user-images.githubusercontent.com/21790/50381028-fdf1f400-06cf-11e9-8773-9c3f3c73f6ca.png)

**Comment by jmgasper** [comment]
@jiangliwu - The italics looks better, but I'm still seeing an extra new line in the blockquote example, thanks!

**Comment by jiangliwu** [comment]
@jmgasper why code missing in topcoder_updates branch ?
check this MR https://github.com/jmgasper/pxscene/pull/2/files
and code missing in here https://github.com/jmgasper/pxscene/blob/topcoder_updates/mime/components/markdown.js#L1323

it should be like this ![image](https://user-images.githubusercontent.com/1697481/50441000-a227a500-0933-11e9-95a4-2446a8a6ba49.png)

**Comment by jiangliwu** [comment]
i see you ignored codes in here , i will create new MR soon .https://github.com/jmgasper/pxscene/commit/2b43769ed679bbb1edcfa0176ea9b85247dfba33#diff-ff2ef5c2981f11f9f17a31f6cf818c8cL1863

**Comment by jiangliwu** [comment]
@jmgasper new MR pushed. https://github.com/jmgasper/pxscene/pull/6
