### ISSUE TITLE
[$375] Support for images in tables

### ISSUE THREAD

**Issue by jmgasper** [topcoderinc/pxCore#259]
@billsedison - We need to update the table support to properly render with images in the table.  We can use Github as a guide for how this should work.

We'll wait until the changes from @jiangliwu have been applied and then we'll work on this.

**Comment by jmgasper** [comment]
@billsedison - Check my fork for the latest:  https://github.com/jmgasper/pxscene

**Comment by billsedison** [comment]
@jmgasper

FYI, some remaining issues in the latest fix of 

(1)
The following table renders incorrect https://github.com/jmgasper/pxscene/tree/topcoder_updates

```
| Default  |  Left    | Center   | Right    |
|----------|:---------|:--------:|---------:|
| 100      |    200   | 300      | 400      |
| 100      |    200   | 300      |
| 100      |    200   | 300      | 400      |  should not be rendered |
```
In pxscene
` should not be rendered` should be removed.
![image](https://user-images.githubusercontent.com/5657467/50412781-159eb900-0845-11e9-8964-c5adc5a8d790.png)


In GitHub

| Default  |  Left    | Center   | Right    |
|----------|:---------|:--------:|---------:|
| 100      |    200   | 300      | 400      |
| 100      |    200   | 300      |
| 100      |    200   | 300      | 400      |  should not be rendered |

I'll fix this issue and include the fix in my PR.

(2)

`xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx` is a single link with line wrapping, but there are two highlight rectangles.

![image](https://user-images.githubusercontent.com/5657467/50412793-39fa9580-0845-11e9-9c45-54e78d9079f5.png)

Do you think is it fine? Or should be it rendered like my version - use a single large rectangle to surround it?
![image](https://user-images.githubusercontent.com/5657467/50412862-b42b1a00-0845-11e9-99d5-9bf8d66daffc.png)

**Comment by billsedison** [comment]
Done https://github.com/jmgasper/pxscene/pull/3

The issue (1) about table text overlapped was also fixed in the PR.

The issue (2) about link highlight rectangle was not fixed, I'll fix it if you want.

**Comment by jmgasper** [comment]
Yeah, lets fix the link rectangle as well, thanks.  I'll bump the payment accordingly.

**Comment by jiangliwu** [comment]
for link, i think need consider this if use one rectangle for two lines.
![image](https://user-images.githubusercontent.com/1697481/50414993-95338480-0853-11e9-9514-1d0c4cd034a9.png)

**Comment by billsedison** [comment]
@jmgasper 

A new bug was observed

![image](https://user-images.githubusercontent.com/5657467/50417262-49d3a300-0860-11e9-837e-951e5d58d365.png)

For some markdown file, if we use `tab` to navigate forward links, the highlight rectangle might be not fully visible in the links of the last line.

Note it won't be able to reproduce on all markdown files, but it can be reproduced consistently in my provided sample markdown  https://github.com/jmgasper/pxscene/blob/755e3f7f07948a2603fef70bb7e99807cfe8bec1/examples/px-reference/text/table-sample.md

I'll fix this issue too.

**Comment by billsedison** [comment]
Done 

https://github.com/jmgasper/pxscene/pull/4
