### ISSUE TITLE
Windows Build - Investigate Breakpad

### ISSUE THREAD

**Issue by jmgasper** [topcoderinc/pxCore#48]
The client has asked us to investigate Breakpad integration:

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&cad=rja&uact=8&ved=0ahUKEwjd8aS51MXTAhXszIMKHVJ6A6sQFgg2MAM&url=https%3A%2F%2Fchromium.googlesource.com%2Fbreakpad%2Fbreakpad%2F&usg=AFQjCNELvHFkou0gfevaNyhc8nUqpgofFw

**Comment by cjalmeida** [comment]
I'm not very familiar with it too, but I'll take a look.

**Comment by jmgasper** [comment]
@cjalmeida - I think this a little broken on Mac

```
pxScene.cpp:34:10: fatal error: 'breakpadSupport.h' file not found
#include "breakpadSupport.h"
         ^
1 error generated.
make: *** [obj/pxScene.o] Error 1
```

Can you double check the build.sh please?  The ./configure / make flow works on a Mac, but it still doesn't seem to find the header file.

**Comment by cjalmeida** [comment]
Ok. I'll investigate and patch it.

Em 2 de mai de 2017 02:24, "Justin Gasper" <notifications@github.com>
escreveu:
